# Generated by Django 4.2 on 2023-04-07 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doornot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('detail', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='DUE_DATE')),
                ('to_day', models.DateField(auto_now=True, null=True)),
                ('doornot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appTodolist.doornot')),
            ],
        ),
    ]
