# Generated by Django 4.2 on 2023-04-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMix', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mixed_word',
        ),
    ]
