# Generated by Django 4.2 on 2023-04-22 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMix', '0002_delete_mixed_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='word1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_word1', to='appMix.word'),
        ),
        migrations.AddField(
            model_name='item',
            name='word2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_word2', to='appMix.word'),
        ),
        migrations.AddField(
            model_name='item',
            name='word3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_word3', to='appMix.word'),
        ),
    ]
