# Generated by Django 4.2 on 2023-04-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMix', '0003_item_word1_item_word2_item_word3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='word1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='word2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='word3',
            field=models.TextField(),
        ),
    ]
