# Generated by Django 4.2 on 2023-04-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMix', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
