# Generated by Django 4.1.7 on 2023-04-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='comment',
        ),
    ]
